// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace orders_system.Models
{
    public partial class Order
    {
        public Order()
        {
            Users = new HashSet<User>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("date", TypeName = "date")]
        public DateTime Date { get; set; }
        [Column("total_price")]
        public double TotalPrice { get; set; }
        [Column("description")]
        [StringLength(50)]
        public string? Description { get; set; }
        [Column("user_id")]
        public int UserId { get; set; }

        [InverseProperty("UserRole")]
        public virtual ICollection<User> Users { get; set; }
    }
}