// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace orders_system.Models
{
    public partial class User
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("user_name")]
        [StringLength(50)]
        public string UserName { get; set; } = null!;
        [Column("first_name")]
        [StringLength(50)]
        public string? FirstName { get; set; }
        [Column("last_name")]
        [StringLength(50)]
        public string? LastName { get; set; }
        [Column("email")]
        [StringLength(50)]
        public string Email { get; set; } = null!;
        [Column("phone_number")]
        [StringLength(50)]
        public string? PhoneNumber { get; set; }
        [Column("fax")]
        [StringLength(50)]
        public string? Fax { get; set; }
        [Column("company_name")]
        [StringLength(50)]
        public string? CompanyName { get; set; }
        [Column("address")]
        [StringLength(50)]
        public string? Address { get; set; }
        [Column("user_role_id")]
        public int UserRoleId { get; set; }
        [Column("password_hash")]
        [MaxLength(256)]
        public byte[]? PasswordHash { get; set; }
        [Column("password_salt")]
        [MaxLength(256)]
        public byte[]? PasswordSalt { get; set; }

        [ForeignKey("UserRoleId")]
        [InverseProperty("Users")]
        public virtual Order UserRole { get; set; } = null!;
        [ForeignKey("UserRoleId")]
        [InverseProperty("Users")]
        public virtual UserRoleType UserRoleNavigation { get; set; } = null!;
    }
}