// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace orders_system.Models
{
    public partial class User
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("user_name")]
        [StringLength(50)]
        public string UserName { get; set; } = null!;
        [Column("email")]
        [StringLength(50)]
        public string Email { get; set; } = null!;
        [Column("password")]
        [StringLength(50)]
        public string Password { get; set; } = null!;
        [Column("user_role_id")]
        public int UserRoleId { get; set; }

        [ForeignKey("UserRoleId")]
        [InverseProperty("Users")]
        public virtual Order UserRole { get; set; } = null!;
        [ForeignKey("UserRoleId")]
        [InverseProperty("Users")]
        public virtual UserRoleType UserRoleNavigation { get; set; } = null!;
    }
}